//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public System.Guid ComponentId { get; set; }
        public string ComponentName { get; set; }
        public string ComponentModel { get; set; }
        public System.Guid Provider { get; set; }
        public Nullable<System.Guid> UsedBy { get; set; }
    }
}
